services:
    - type: web
    name: topupking-bank-3
    env: php
    buildCommand: composer install --no-dev --optimize-autoloader
    startCommand: php -S 0.0.0.0:$PORT -t public
    envVars:
            - key: APP_ENV
        value: production
            - key: APP_DEBUG
        value: false
